Adiciona arquivos de guidelines de contribuição
OpenDevUFCG/laguinho-cli pull request #11
Opened 2019-09-03 04:12 UTC by thayannevls

#### Issue Relacionada
Resolves #6 

#### Qual o propósito dessa pull request?
Apenas criação inicial dos arquivos citados na issue. 

#### Tipo de mudanças

✔️ | Tipo de mudança
---|---
_ | Bug fix 
✔️ | Nova feature 
_ | Breaking change 
_ | Refatoração 

#### Notas

Vamo que vamo

2019-09-03 05:09 UTC, JoseRenan reviewed
Tu poderia me explicar o que seria esse DESIGN_DOCS, @thayannevls? Pq ele me parece com informações que poderiam estar no readme

2019-09-03 17:01 UTC, thayannevls commented
Seria um docs pra explicar o flow arquitetural inteiro do laguinho, não da cli.

Pode ser uma wiki também, vcs que decidem. Só subi pra relembrar de documentar isso

2019-09-04 20:27 UTC, JoseRenan requested changes

2019-09-04 20:27 UTC, JoseRenan commented on CHANGELOG.md
> +## [Não publicado]
Como ainda não temos uma versão inicial, todo o código tá indo direto pro master, sendo assim, tipo, acho que o não publicado não se encaixa pra agora 🤔 já que as alterações acabam sendo publicadas indiretamente

2019-09-04 20:27 UTC, JoseRenan commented on CHANGELOG.md
> +## [Não publicado]
No caso o ideal seria já botar v0.1.0

2019-10-04 01:40 UTC, JoseRenan approved these changes

2019-10-04 01:40 UTC, merged