Adicao publish interativo
OpenDevUFCG/laguinho-cli pull request #19
Opened 2019-09-06 16:30 UTC by jessescn

#### Issue Relacionada
Issue #13 

#### Qual o propósito dessa pull request?

Adicionar o menu interativo dentro do comando publish

#### Como pode ser manualmente testado?

executando o comando pipenv run laguinho-dev publish

#### Screenshots ou exemplos de uso

![publishla](https://user-images.githubusercontent.com/33502846/64444295-3a248380-d0aa-11e9-9b9e-d138ae655e61.png)

#### Tipo de mudanças

✔️ | Tipo de mudança
---|---
_ | Bug fix 
_ | Nova feature 
✔️ | Breaking change 
_ | Refatoração

2019-09-06 23:18 UTC, JoseRenan requested changes

2019-09-06 23:18 UTC, JoseRenan commented on laguinho/commands/publish.py
> +    metadats['contributable'] = click.prompt("Os dados são contribuíveis?" , type=bool, default=True)
Aqui podia ser uma confirmação [y/N]

2019-09-06 23:18 UTC, JoseRenan commented on laguinho/commands/publish.py
> +
Seria bom fazer uma validação de se o arquivo laguinho.json já existe e pular o form dizendo "Arquivo laguinho.json já foi criado"

2019-09-06 23:18 UTC, JoseRenan commented on laguinho/commands/publish.py
> +    metadats = {}
O nome da variável devia ser metadata não?

2019-09-06 23:18 UTC, JoseRenan commented on laguinho/commands/publish.py
> +    metadats['name'] = click.prompt('\nNome do dataset', type=str, default="default")
O default poderia ser o nome da pasta atual talvez, como o NPM faz :thinking: se não for o caso, podemos tirar o default daqui mesmo

2019-09-06 23:18 UTC, JoseRenan commented on laguinho/commands/publish.py
> +    metadats['url'] = click.prompt('Url do diretório', type=str)
`URL` (em caps) e seria do `repositório no gihub` no caso, né? seria bom pra informar que só suportamos github por enquanto

2019-09-06 23:18 UTC, JoseRenan commented on laguinho/commands/publish.py
> +    metadats['path'] = click.prompt("Caminho da raiz até o diretório onde está o dataset", type=str, default="./")
Podemos/devemos considerar o caminho relativo mesmo :thinking: já que vamos pegar esses arquivos direto do repositório, o path da raiz até o dataset não vai ser muito útil eu acho

2019-09-06 23:18 UTC, JoseRenan commented on laguinho/commands/publish.py
> +    metadats['data_format'] = click.prompt("Formato do arquivo", type=str, default="csv")
dos arquivos*

2019-09-06 23:27 UTC, jessescn commented on laguinho/commands/publish.py
> +
Eu levei como base o npm init msm, ele não checa. Eu pensei em deixar pra caso ele queira alterar algo, se bem que ele pode ir manualmente

2019-09-06 23:30 UTC, jessescn commented on laguinho/commands/publish.py
> +    metadats['path'] = click.prompt("Caminho da raiz até o diretório onde está o dataset", type=str, default="./")
Então no caso ele so passa a URL da raiz, e a gente vai procurar pelo dataset?

2019-09-06 23:40 UTC, JoseRenan commented on laguinho/commands/publish.py
> +    metadats['path'] = click.prompt("Caminho da raiz até o diretório onde está o dataset", type=str, default="./")
A raiz é ambíguo aqui, porque o usuário pode pensar que é a raiz do sistema e não do repositório

2019-09-06 23:45 UTC, jessescn commented on laguinho/commands/publish.py
> +    metadats['path'] = click.prompt("Caminho da raiz até o diretório onde está o dataset", type=str, default="./")
Nesse caso, tu acha melhor tirar ou deixar mais claro? porque sabendo o path de onde ta o dataset creio que fica melhor pra galera do back navegar pelos repositorios no github.

2019-09-06 23:48 UTC, jessescn commented on laguinho/commands/publish.py
> +
Posso adicionar uma verificação tipo "Arquivo laguinho.json já existe. Deseja sobrescrever? [y/N]"

2019-09-07 00:28 UTC, JoseRenan commented on laguinho/commands/publish.py
> +
Pode serr, top

2019-09-07 00:28 UTC, JoseRenan commented on laguinho/commands/publish.py
> +    metadats['path'] = click.prompt("Caminho da raiz até o diretório onde está o dataset", type=str, default="./")
Deixar mais claro msm

2019-09-07 01:22 UTC, jessescn commented on laguinho/commands/publish.py
> +    metadats['path'] = click.prompt("Caminho da raiz até o diretório onde está o dataset", type=str, default="./")
tens alguma sugestão? kkkk

2019-09-07 01:23 UTC, jessescn commented on laguinho/commands/publish.py
> +    metadats['name'] = click.prompt('\nNome do dataset', type=str, default="default")
Coloquei a pasta atual, faz mais sentido msm

2019-09-07 02:24 UTC, JoseRenan approved these changes

2019-09-07 02:25 UTC, merged