Criação do comando publish
OpenDevUFCG/laguinho-cli pull request #20
Opened 2019-09-06 16:52 UTC by ArthurFerrao

#### Issue Relacionada

Resolve #12 

#### Qual o propósito dessa pull request?

Adiciona ao cli o comando publish com seu help.

#### Tipo de mudanças

✔️ | Tipo de mudança
---|---
_ | Bug fix 
✔️ | Nova feature 
_ | Breaking change 
_ | Refatoração

2019-09-07 03:12 UTC, JoseRenan requested changes

2019-09-07 03:12 UTC, JoseRenan commented on laguinho/commands/publish.py
> +    """Publica dataset de um repositório do github no laguinho que estará disponível para ser acessado."""
`Publica um dataset no laguinho para que possa ser baixado por outras pessoas por meio do comando get` fica melhor não?

2019-09-07 03:17 UTC, JoseRenan commented
@ArthurFerrao, tu podia aproveitar que o #19 já foi merjado e adiciona no comando? Tipo, agora a mensagem ser `Iniciando publish no laguinho` e chamar o `init_laguinho` que @jessescn criou e depois disso falar que é uma feature em desenvolvimento e que ele não será publicado de fato

2019-09-08 18:55 UTC, ArthurFerrao commented on laguinho/commands/publish.py
> +    """Publica dataset de um repositório do github no laguinho que estará disponível para ser acessado."""
Acho que fica melhor mesmo, explica mais o que é "ser acessado". Vou mudar isso.

2019-09-08 20:23 UTC, JoseRenan approved these changes
Toppp meu patrão!!!

2019-09-08 20:25 UTC, merged