Adiciona função para o download do dataset
OpenDevUFCG/laguinho-cli pull request #24
Opened 2019-09-12 17:05 UTC by jessescn

#### Issue Relacionada
Issue #22 

#### Qual o propósito dessa pull request?

A pull request tem como função integrar o código referente ao download do dataset a partir dos metadados cadastrados no comando publish. 
   
#### Como pode ser manualmente testado?

Como o objetivo da issue é apenas a criação da função para download. Dentro da função get do arquivo get.py tem um metadata estático, caso queira testar um data diferente, só precisa alterar esses dados. Após isso, só é necessário rodar o comando de GET

``` bash
$ pipenv run laguinho-dev get [NAME]
```
  

#### Tipo de mudanças

✔️ | Tipo de mudança
---|---
_ | Bug fix 
_ | Nova feature 
✔️ | Breaking change 
_ | Refatoração 

#### Notas

Foi adicionado docstrings as funções a partir do [Styleguide](https://google.github.io/styleguide/pyguide.html) fornecido pelo Google.

2019-10-04 01:33 UTC, JoseRenan requested changes

2019-10-04 01:33 UTC, JoseRenan commented on laguinho/commands/get.py
> +    """Contrói a URL da API
Constrói*

2019-10-04 01:33 UTC, JoseRenan commented on laguinho/commands/get.py
> +        click.echo('\nVocê alcançou sua cota máxima de downloads disponíveis pelo Github. Caso queira aumenta-la, acesse nosso github e leia a sessão limite de donwloads no README!.\n')
Qual sessão limite de downloads?

2019-10-04 01:33 UTC, JoseRenan commented on laguinho/commands/get.py
> +    if not request_file:
Tu poderia me explicar melhor porque esses dois tipos de retorno? Não tem alguma forma de dividir em duas funções? encapsulando a parte que é igual mas diferenciando o retorno

2019-10-04 01:42 UTC, JoseRenan commented
Ahh, seria bom já adicionar uma entry no changelog de que isso foi adicionado

2019-10-04 01:59 UTC, jessescn commented on laguinho/commands/get.py
> +        click.echo('\nVocê alcançou sua cota máxima de downloads disponíveis pelo Github. Caso queira aumenta-la, acesse nosso github e leia a sessão limite de donwloads no README!.\n')
A que eu vou adicionar, mas brincadeira, esqueci de tirar essa parte. Se bem que valia a pena ter algum canto falando sobre isso, mas pode ser quando a gente for discutir em relação a como vai ficar essa questão da limitação de requests.

2019-10-04 02:08 UTC, jessescn commented on laguinho/commands/get.py
> +    if not request_file:
era só porque no método create_file, ele precisa da response.content para escrever no arquivo, enquanto que nos outros dois lugares que também são chamados, eles tem que fazer um json.loads() desse response.content. Pode ser uma opção criar um método pra cada ou deixar eles fazerem json.loads na response msm.

2019-10-04 03:58 UTC, JoseRenan commented on laguinho/commands/get.py
> +        click.echo('\nVocê alcançou sua cota máxima de downloads disponíveis pelo Github. Caso queira aumenta-la, acesse nosso github e leia a sessão limite de donwloads no README!.\n')
Então a gente deixa uma issue criada pra isso, aproveitar o hacktoberfest, vai que tem um profissional em github API por aí querendo completar os PR pra ganhar camisa...

2019-10-04 03:59 UTC, JoseRenan commented on laguinho/commands/get.py
> +    if not request_file:
Tu acha que esse load vai precisar fazer em mais lugares? se sim, cria o método, senão, deixa o load lá, pra gente nn ter de fazer aquele isinstance :'(

2019-10-04 13:50 UTC, jessescn commented on laguinho/commands/get.py
> +    if not request_file:
Por enquanto ele só usa em dois cantos, acho que é válido adicionar os loads mesmo. Talvez caso seja necessário fazer isso no futuro a gente pode pensar em adicionar um método pra isso.

2019-10-13 17:04 UTC, JoseRenan approved these changes

2019-10-13 17:05 UTC, merged