Adicao do codigo restante da validacao
OpenDevUFCG/laguinho-cli pull request #28
Opened 2019-10-26 01:39 UTC by jessescn

#### Qual o propósito dessa pull request?

Adicionar o restante das alterações para a validação dos inputs do comando publish, essas alterações tem como objetivo separar de uma maneira melhor a logica de validação dos métodos

#### Tipo de mudanças

✔️ | Tipo de mudança
---|---
✔️ | Bug fix 
_ | Nova feature 
_ | Breaking change 
_ | Refatoração

2019-10-27 03:01 UTC, JoseRenan requested changes

2019-10-27 03:01 UTC, JoseRenan commented on laguinho/utils/validations.py
> +    return isinstance(contents, list)
Esse isinstance é pq se nn for lista vem é um erro? Não seria melhor checar o status da requisição?

2019-10-27 20:31 UTC, jessescn commented on laguinho/utils/validations.py
> +    return isinstance(contents, list)
Corrigido :)

2019-10-28 01:29 UTC, JoseRenan requested changes

2019-10-28 01:29 UTC, JoseRenan commented on laguinho/utils/validations.py
> +    if len(url.split('/')) < 3:
hmm, isso retorna false se eu tiver a URL `https://github.com/OpenDevUFCG/laguinho` é esperado?

2019-10-28 01:48 UTC, jessescn commented on laguinho/utils/validations.py
> +    if len(url.split('/')) < 3:
Ele retorna true, já que é uma url válida. Se tu tais dizendo isso por causa do `username`, eu esqueci de por no comentário que pode ser uma organizacão também.

2019-10-28 01:58 UTC, JoseRenan approved these changes
toppp

2019-10-28 01:58 UTC, merged